# Generated by Django 4.0.6 on 2022-07-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("surname", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("date_birth", models.DateField(verbose_name="Дата рождения")),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("integer_field", models.IntegerField()),
                ("positive_field", models.PositiveIntegerField()),
                ("positive_small_field", models.PositiveSmallIntegerField()),
                ("big_integer_field", models.BigIntegerField()),
                ("float_field", models.FloatField()),
                ("binary_field", models.BinaryField()),
                ("boolean_field", models.BooleanField()),
                ("char_field", models.CharField(max_length=5)),
                ("text_field", models.TextField(max_length=20)),
                ("date_field", models.DateField()),
                ("date_time_field", models.DateTimeField()),
                ("decimal_field", models.DecimalField(decimal_places=2, max_digits=8)),
                ("email", models.EmailField(max_length=254)),
                ("file_field", models.FileField(upload_to="file")),
                ("image_field", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "place",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="models.place",
                    ),
                ),
                ("serves_hot_dogs", models.BooleanField(default=False)),
                ("serves_pizza", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("text", models.TextField(max_length=1000)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("comedy", "Comedy"),
                            ("tragedy", "Tragedy"),
                            ("drama", "Drama"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="models.author"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=100)),
                ("publications", models.ManyToManyField(to="models.publication")),
            ],
            options={
                "ordering": ("headline",),
            },
        ),
        migrations.CreateModel(
            name="Waiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.restaurant",
                    ),
                ),
            ],
        ),
    ]
