# Generated by Django 4.0.6 on 2022-08-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
